name: UnitTests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # launches every Monday at midnight
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        redis-version: [ 7 ]
        python-version: [ '3.11', '3.12', '3.13' ]
        architecture: [ 'x64' ]

    steps:
      - name: Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
          redis-password: ${{ secrets.REDIS_PSW }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          check-latest: true

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        env:
          REDIS_PSW: ${{ secrets.REDIS_PSW }}
        run: |
          cd tests || exit 1
          echo "REDIS_PSW=${REDIS_PSW}" >> redis.env

      - name: Run UnitTests
        run: |
          cd tests || exit 1
          python -m unittest test_units_1.py test_units_2.py test_units_3.py
